# Generated by Django 4.0.1 on 2022-03-18 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_sex', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Prefer Not to Say')], default=0)),
                ('current_age_range', models.IntegerField(choices=[(0, 'Under 18'), (1, '18-35'), (2, '36-55'), (3, '56-75'), (4, 'Over 75')], default=0)),
                ('current_test_status', models.BooleanField(null=True)),
                ('recent_test_date', models.IntegerField(blank=True, null=True)),
                ('current_test_result', models.BooleanField(null=True)),
                ('current_body_temp', models.DecimalField(blank=0, decimal_places=2, default=-1, max_digits=120)),
                ('current_weight', models.DecimalField(blank=0, decimal_places=2, default=100, max_digits=6)),
                ('current_self_assessment', models.IntegerField(choices=[(0, 'Very_Bad'), (1, 'Bad'), (2, 'Ok'), (3, 'Good'), (4, 'Very_Good')], default=0)),
                ('current_symptoms', models.TextField(blank=0, default='None')),
                ('current_vaxination_count', models.IntegerField(blank=0, default=0)),
                ('is_prioritized', models.BooleanField(default=False, verbose_name='is_prioritized')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(null=True)),
                ('user_identity', models.CharField(choices=[('1', 'Doctor'), ('2', 'Patient'), ('3', 'Immigration Officer'), ('4', 'Health Official'), ('5', 'Administrator')], max_length=500, verbose_name='Category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='user_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='users.userinfo'),
        ),
        migrations.CreateModel(
            name='HealthOfficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.TextField(blank=True, max_length=500, null=True)),
                ('user_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_official', to='users.userinfo')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='user_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='users.userinfo'),
        ),
        migrations.CreateModel(
            name='Admin_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(blank=True, choices=[('1', 'Staff'), ('2', 'Admin')], max_length=500, null=True)),
                ('user_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Admin', to='users.userinfo')),
            ],
        ),
    ]
