# Generated by Django 4.0.1 on 2022-03-18 01:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDailyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Prefer Not to Say')], default=0)),
                ('age_range', models.IntegerField(choices=[(0, 'Under 18'), (1, '18-35'), (2, '36-55'), (3, '56-75'), (4, 'Over 75')], default=0)),
                ('test_status', models.BooleanField(null=True)),
                ('recent_test_date', models.IntegerField(blank=True, null=True)),
                ('test_result', models.BooleanField(null=True)),
                ('body_temp', models.DecimalField(blank=0, decimal_places=2, default=-1, max_digits=120)),
                ('weight', models.DecimalField(blank=0, decimal_places=2, default=100, max_digits=6)),
                ('self_assessment', models.IntegerField(choices=[(0, 'Very_Bad'), (1, 'Bad'), (2, 'Ok'), (3, 'Good'), (4, 'Very_Good')], default=0)),
                ('symptoms', models.TextField(blank=0, default='None')),
                ('vaxination_count', models.IntegerField(blank=0, default=0)),
                ('comments', models.TextField(blank=0, default='None')),
            ],
        ),
        migrations.CreateModel(
            name='PatientStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateField(default=datetime.date.today)),
                ('current_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='users.patient')),
                ('patient_form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='patientStuff.patientdailyform')),
            ],
        ),
    ]
