# Generated by Django 4.0.1 on 2022-03-18 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmigrationOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='immigration', to='users.userinfo')),
            ],
        ),
    ]
